// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1591644005);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1591644126);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1591643643);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1591643763);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1591643883);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1591643673);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1591643613);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{550f6b34-f195-46f7-a1a9-2ff3630e9b20}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1591643664153");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1591645473153");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1591643637625");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1591647237625");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1591643646");
user_pref("browser.slowStartup.averageTime", 23565);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200407103758");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1591643623);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1591643638351");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "5b3e1850d759453fb4177d74be539838");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1591644016);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e3766a7b-c579-4668-9260-a92c593316d4\",\"formautofill@mozilla.org\":\"3e602c41-8693-464c-89c8-f0bd477cfc99\",\"screenshots@mozilla.org\":\"82d091a8-0e49-49ff-9a3c-8ee1c0d109e3\",\"webcompat-reporter@mozilla.org\":\"762ebc48-a5a0-4103-a059-af6bcc17afc9\",\"webcompat@mozilla.org\":\"016bbead-6031-433f-b78e-0b266ef346ea\",\"default-theme@mozilla.org\":\"4004fcf9-172c-4001-981a-0041aa5eb5a9\",\"google@search.mozilla.org\":\"4e92ff70-bfd1-4d7d-b9d5-4e8eefa6d15f\",\"amazon@search.mozilla.org\":\"985f25a5-564f-4c8a-9e23-53586d9ee479\",\"bing@search.mozilla.org\":\"5d89a42d-3240-46db-8d43-f91991438bb7\",\"ddg@search.mozilla.org\":\"4ef8bf3d-965c-46ea-8e61-41fd857e0212\",\"ebay@search.mozilla.org\":\"d02b1ca0-66db-4e32-88cb-bff9c820d326\",\"twitter@search.mozilla.org\":\"9c6badf3-159a-45f5-b2f6-7eee50648329\",\"wikipedia@search.mozilla.org\":\"8b44452a-1581-4827-9ed5-8bacb14a1074\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1591643940);
user_pref("media.gmp-manager.buildID", "20200407103758");
user_pref("media.gmp-manager.lastCheck", 1591643777);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1591643946);
user_pref("places.history.expiration.transient_current_max_pages", 80870);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1591643776);
user_pref("security.remote_settings.intermediates.checked", 1591643776);
user_pref("security.sandbox.content.tempDirSuffix", "2dc1c4f6-7b81-4723-9bea-0122b0187e55");
user_pref("security.sandbox.plugin.tempDirSuffix", "280e63db-058f-4834-a5ce-f65ade48c4a1");
user_pref("services.blocklist.addons.checked", 1591643776);
user_pref("services.blocklist.gfx.checked", 1591643776);
user_pref("services.blocklist.pinning.checked", 1591643776);
user_pref("services.blocklist.plugins.checked", 1591643776);
user_pref("services.settings.clock_skew_seconds", -49);
user_pref("services.settings.last_etag", "\"1591632240155\"");
user_pref("services.settings.last_update_seconds", 1591643934);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1591643776);
user_pref("services.settings.main.cfr-fxa.last_check", 1591643776);
user_pref("services.settings.main.cfr.last_check", 1591643776);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1591643776);
user_pref("services.settings.main.hijack-blocklists.last_check", 1591643776);
user_pref("services.settings.main.language-dictionaries.last_check", 1591643776);
user_pref("services.settings.main.public-suffix-list.last_check", 1591643776);
user_pref("services.settings.main.sites-classification.last_check", 1591643776);
user_pref("services.settings.main.tippytop.last_check", 1591643776);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1591643776);
user_pref("services.settings.main.whats-new-panel.last_check", 1591643776);
user_pref("services.settings.security.onecrl.checked", 1591643776);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1591643943);
user_pref("toolkit.startup.last_success", 1591643601);
user_pref("toolkit.telemetry.cachedClientID", "4b953b4f-f93c-4d50-8e52-d45034577289");
user_pref("toolkit.telemetry.previousBuildID", "20200407103758");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
